[workspace]
members = ["client", "server"]

[package]
name = "server"
version = "0.1.0"
edition = "2018"
[[bin]]
name = "server"
path = "server/main.rs"

[dependencies]


[package]
name = "client"
version = "0.1.0"
edition = "2018"
[[bin]]
name = "client"
path = "client/main.rs"

[dependencies]