[package]
name = "nebula_server"
version = "0.1.0"
edition = "2018"
resolver = "2"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
tokio-postgres = "0.7"
kvptree = { git = "https://github.com/iKramp/KVPTree.git"}
anyhow = "1.0"